apiVersion: apps/v1
kind: Deployment
metadata: 
 name: v2-frontend-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
   component: frontend
 template:
  metadata:
   labels:
    component: frontend
  spec:
   containers:
    - name: frontend
      image: tericai/frontend
      ports:
       - containerPort: 3500
      env:
       - name: HOST_URL
         value: '192.168.99.110'

---
apiVersion: v1
kind: Service
metadata:
 name: v2-frontend-clusterip
spec:
 type: NodePort
 selector:
  component: frontend
 ports:
  - port: 3500
    targetPort: 80
    nodePort: 30000
    
