apiVersion: apps/v1
kind: Deployment
metadata: 
 name: v2-go-thumbnails-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
   component: thumbnails
 template:
  metadata:
   labels:
    component: thumbnails
  spec:
   containers:
    - name: v2-go-thumbnails
      image: tericai/v2_go_thumbnails
      env:
       - name: RABBIT_MQ_HOST
         value: 54.169.103.232:5672
       - name: RABBIT_MQ_USER
         value: zest
       - name: RABBIT_MQ_PASSWORD
         value: iot
       - name: DATASET_DB_HOST
         value: 54.169.103.232:27019
       - name: DATASET_DB_NAME
         value: ms_dataset
       - name: LICENSE_SERVER
         value: http://52.74.93.83:8081
       - name: DEFAULT_DATASOURCE_ID
         value: 5d4d9738532e40002c316f67
       - name: DEBUG_MODE
         value: '3'
       - name: THUMBNAIL_SIZES
         value: 75,200
