apiVersion: apps/v1
kind: Deployment
metadata: 
 name: v2-go-project-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
   component: project
 template:
  metadata:
   labels:
    component: project
  spec:
   containers:
    - name: v2-go-project
      image: tericai/v2_go_project
      env:
       - name: RABBIT_MQ_HOST
         value: 54.169.103.232:5672
       - name: RABBIT_MQ_USER
         value: zest
       - name: RABBIT_MQ_PASSWORD
         value: iot
       - name: PROJECT_DB_HOST
         value: 54.169.103.232:27019
       - name: PROJECT_DB_NAME
         value: ms_project
       - name: LICENSE_SERVER
         value: http://52.74.93.83:8081
       - name: DEBUG_MODE
         value: '3'
